### ISSUE TITLE
Buffer Not Defined

### ISSUE THREAD

**Issue by alteredorange** [Hackdoor-io/imgproxy-js#3]
Heyo, I've been looking for something just like this, having a heck of a time getting an imgproxy url configured.  I'm trying to use your plugin with Svelte, but I get a buffer is not defined error.  I tried using 

import { default as B } from "buffer/";
const { Buffer } = B;

but then I get a buffer$1 is not defined. Do I have to do anything special to make this work? Thanks for the help!

**Comment by micheleriva** [comment]
Hi @alteredorange ,
thanks for reporting that!

It seems a bug, I'll investigate on it and I'll keep you update.

**Comment by alteredorange** [comment]
Hi Michele,

I think this is just a Rollup related issue because you're using "require"
and Rollup doesn't like that.

**Comment by alteredorange** [comment]
Hello! I finally got url generation working with rollup, I needed to use a different library, since rollup hated the create-hmac one :)  I managed to get it working with `npm install hash.js` and replacing the const hmac line with 
 `const hmac = hash.hmac(hash.sha256, hexDecode(secret));`

Thanks and have a great week!
